# Generated by Django 2.2.9 on 2020-12-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
