# Generated by Django 2.2.9 on 2020-11-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20200729_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('delivery', 'Delivery')], max_length=9)),
                ('country', models.CharField(default='Kenya', max_length=252)),
                ('city', models.CharField(max_length=252)),
                ('locale', models.CharField(max_length=252)),
                ('pick_point', models.CharField(max_length=252)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['city'],
            },
        ),
    ]
