# Generated by Django 2.2.9 on 2020-07-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_creation',
            new_name='profile_creation_complete',
        ),
    ]
