# Generated by Django 2.2.9 on 2020-07-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200729_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_type',
            new_name='account_type',
        ),
    ]
