# Generated by Django 2.2.9 on 2020-08-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='total',
        ),
    ]
