# Generated by Django 2.2.9 on 2020-11-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201106_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchitem',
            name='owner',
        ),
    ]
