# Generated by Django 2.2.9 on 2020-08-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bag', '0002_remove_bagitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
