# Generated by Django 2.2.9 on 2020-11-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_bag_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bag.Bag'),
        ),
    ]
