# Generated by Django 2.2.9 on 2020-12-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0004_auto_20201106_0953'),
        ('users', '0004_auto_20200729_2130'),
        ('products', '0001_initial'),
        ('orders', '0002_auto_20201213_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=36)),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('refunded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag.BagItem')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Store')),
            ],
            options={
                'db_table': 'purchased_product',
                'ordering': ['-created_at'],
            },
        ),
    ]
