# Generated by Django 2.2.9 on 2020-11-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0004_auto_20200729_2130'),
        ('bag', '0004_auto_20201106_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=36)),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('refunded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag.BagItem')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=36)),
                ('gift_recipient', models.CharField(max_length=252, null=True)),
                ('delivery', models.CharField(choices=[(1, 'No Delivery, ill pick them myself'), (2, 'Yes, Deliver to me')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('refund', 'Refund')], default='created', max_length=9)),
                ('delivery_total', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=1, default=0.0, max_digits=12)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField(default=False)),
                ('bag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bag.Bag')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='addresses.Address')),
            ],
        ),
    ]
